// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1jFso89XKcrPPTxOgstVKR9h6pV7QhUw',
    appId: '1:1037863461329:android:2ccade9f730c099e58c0f0',
    messagingSenderId: '1037863461329',
    projectId: 'pathbook-7c13e',
    storageBucket: 'pathbook-7c13e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9GK3mzFf0CarTlDZrepqpuyDd9cUsLqA',
    appId: '1:1037863461329:ios:4d44f95d2b4ce83e58c0f0',
    messagingSenderId: '1037863461329',
    projectId: 'pathbook-7c13e',
    storageBucket: 'pathbook-7c13e.firebasestorage.app',
    iosBundleId: 'com.example.pathbooks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTtFf4Glglwu50Fz4DMxTsEfxsmxodkqI',
    appId: '1:1037863461329:web:5f8debb26ebf9da558c0f0',
    messagingSenderId: '1037863461329',
    projectId: 'pathbook-7c13e',
    authDomain: 'pathbook-7c13e.firebaseapp.com',
    storageBucket: 'pathbook-7c13e.firebasestorage.app',
    measurementId: 'G-QYVYEQ6T37',
  );
}
